_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.11
            "6": 4.51.3
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
batch_size:
    value: 5
data_percentage:
    value: 0.1
emotion_weight:
    value: 0.5
epochs:
    value: 10
learning_rate:
    value: 3e-05
simple_styles:
    value: false
